# include: package:very_good_analysis/analysis_options.yaml

# analyzer:
#   strong-mode:
#       implicit-casts: false
#       implicit-dynamic: false
#   errors:
#     missing_required_param: error
#     missing_return: error
  